import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Check, Globe2, Instagram, MessageCircle, PhoneCall, Radio, RefreshCw, Send, Settings2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const channels = [
  { id: "web" as const, name: "Live chat widget", nameAr: "ودجت الموقع", description: "أضف محادثة ذكية لأي موقع بسطر واحد.", icon: Globe2, tint: "text-cyan-300", bg: "bg-cyan-300/10", ready: true },
  { id: "whatsapp" as const, name: "WhatsApp Business", nameAr: "واتساب للأعمال", description: "استقبل رسائل واتساب ورد عليها من وكيلك.", icon: MessageCircle, tint: "text-lime-300", bg: "bg-lime-300/10", ready: false },
  { id: "messenger" as const, name: "Facebook Messenger", nameAr: "فيسبوك ماسنجر", description: "وحّد رسائل صفحاتك في صندوق واحد.", icon: Send, tint: "text-blue-300", bg: "bg-blue-300/10", ready: false },
  { id: "instagram" as const, name: "Instagram DMs", nameAr: "رسائل إنستغرام", description: "حوّل التفاعل إلى محادثات وفرص مؤهلة.", icon: Instagram, tint: "text-fuchsia-300", bg: "bg-fuchsia-300/10", ready: false },
  { id: "phone" as const, name: "Voice / Phone", nameAr: "الهاتف الصوتي", description: "تجهيز بوابة صوتية للتعامل مع المكالمات.", icon: PhoneCall, tint: "text-amber-300", bg: "bg-amber-300/10", ready: false },
];

export default function Channels() {
  const utils = trpc.useUtils();
  const { data: agents = [] } = trpc.agents.list.useQuery();
  const [agentId, setAgentId] = useState<number | undefined>();
  useEffect(() => { if (!agentId && agents[0]) setAgentId(agents[0].id); }, [agents, agentId]);
  const { data: integrations = [] } = trpc.channels.list.useQuery({ agentId }, { enabled: Boolean(agentId) });
  const configureMutation = trpc.channels.configure.useMutation({ onSuccess: async () => { await utils.channels.list.invalidate(); toast.success("تم تحديث إعداد القناة"); }, onError: error => toast.error(error.message) });
  const activeMap = useMemo(() => new Map(integrations.map(item => [item.channel, item.isActive === 1])), [integrations]);
  const toggle = (channel: typeof channels[number]) => { if (!agentId) return toast.error("اختر وكيلاً أولاً"); if (!channel.ready) return toast.info("سنطلب بيانات القناة عند تفعيل التكامل الرسمي"); configureMutation.mutate({ agentId, channel: channel.id, isActive: !activeMap.get(channel.id) }); };

  return <div className="mx-auto max-w-[1400px] space-y-7 pb-12" dir="rtl"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300/80" dir="ltr">Omnichannel / 04</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">القنوات <span className="text-slate-500">/ Channels</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">اجعل وكيلك حاضراً حيث يتواجد عميلك، مع تحكم واضح في حالة كل قناة وربطها بالوكيل المناسب.</p></div><div className="flex items-center gap-3"><select value={agentId ?? ""} onChange={e => setAgentId(Number(e.target.value))} className="h-10 rounded-xl border border-white/10 bg-white/[0.05] px-3 text-sm text-white outline-none"><option value="" className="bg-[#0b1728]">اختر الوكيل</option>{agents.map(agent => <option key={agent.id} value={agent.id} className="bg-[#0b1728]">{agent.name}</option>)}</select><Badge className="border-lime-300/20 bg-lime-300/10 px-3 py-2 text-lime-200">{integrations.filter(i => i.isActive).length} مفعّلة</Badge></div></header>
  <div className="grid gap-4 lg:grid-cols-2">{channels.map(channel => { const active = activeMap.get(channel.id) ?? false; return <Card key={channel.id} className={`border-white/10 bg-[#0b1728]/90 transition ${active ? "shadow-lg shadow-cyan-950/20" : ""}`}><CardContent className="p-6"><div className="flex items-start gap-4"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl ${channel.bg} ${channel.tint}`}><channel.icon className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-white">{channel.nameAr}</h2><p className="mt-1 text-xs text-slate-500" dir="ltr">{channel.name}</p></div><Badge className={active ? "border-lime-300/20 bg-lime-300/10 text-lime-200" : "border-white/10 bg-white/[0.05] text-slate-400"}>{active ? "Live" : channel.ready ? "Ready" : "Connect"}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-400">{channel.description}</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => toggle(channel)} disabled={configureMutation.isPending} className={active ? "rounded-xl bg-white/10 text-white hover:bg-white/15" : channel.ready ? "rounded-xl bg-cyan-300 text-slate-950 hover:bg-cyan-200" : "rounded-xl bg-white/[0.06] text-slate-300 hover:bg-white/10"}>{active ? <><Check className="ml-2 h-4 w-4" /> مفعّلة</> : channel.ready ? <><Radio className="ml-2 h-4 w-4" /> تفعيل</> : <><Settings2 className="ml-2 h-4 w-4" /> إعداد الربط</>}</Button>{!channel.ready && <Button variant="ghost" className="rounded-xl text-xs text-slate-500 hover:bg-white/5 hover:text-white">قريباً</Button>}</div></div></div></CardContent></Card>; })}</div>
  <Card className="border-white/10 bg-[#0b1728]/90"><CardHeader className="flex flex-row items-center gap-3 border-b border-white/10 pb-5"><RefreshCw className="h-5 w-5 text-cyan-300" /><div><CardTitle className="text-base text-white">كيف تعمل القنوات الرسمية؟</CardTitle><p className="mt-1 text-xs text-slate-400">يستقبل الخادم الأحداث عبر Webhooks موثقة، ثم يمررها إلى الوكيل مع الحفاظ على مساحة العمل.</p></div></CardHeader><CardContent className="grid gap-4 p-5 text-sm text-slate-400 md:grid-cols-3"><div><p className="font-medium text-white">01 · Event intake</p><p className="mt-2 leading-6">كل رسالة تصل إلى نقطة استقبال قناة محددة مع التحقق من التوقيع.</p></div><div><p className="font-medium text-white">02 · Agent routing</p><p className="mt-2 leading-6">تُربط القناة بالوكيل الذي اختاره صاحب مساحة العمل.</p></div><div><p className="font-medium text-white">03 · Human handoff</p><p className="mt-2 leading-6">عند التصعيد، تُحفظ المحادثة وتنتقل للفريق بدلاً من الاستمرار آلياً.</p></div></CardContent></Card></div>;
}
