import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronLeft, Inbox, MessageCircle, Phone, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const channelIcon: Record<string, typeof MessageCircle> = { web: MessageCircle, whatsapp: Phone, messenger: MessageCircle, instagram: MessageCircle, phone: Phone };

export default function Conversations() {
  const utils = trpc.useUtils();
  const { data: conversations = [], isLoading } = trpc.conversations.list.useQuery();
  const [selectedId, setSelectedId] = useState<number | undefined>();
  useEffect(() => { if (!selectedId && conversations[0]) setSelectedId(conversations[0].id); }, [conversations, selectedId]);
  const { data: detail } = trpc.conversations.detail.useQuery({ id: selectedId as number }, { enabled: Boolean(selectedId) });
  const statusMutation = trpc.conversations.setStatus.useMutation({ onSuccess: async () => { await utils.conversations.list.invalidate(); await utils.conversations.detail.invalidate(); toast.success("تم تحديث حالة المحادثة"); }, onError: error => toast.error(error.message) });
  const setStatus = (status: "active" | "escalated" | "resolved") => { if (selectedId) statusMutation.mutate({ id: selectedId, status }); };

  return <div className="mx-auto max-w-[1400px] space-y-7 pb-12" dir="rtl">
    <header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300/80" dir="ltr">Conversation Inbox / 03</p><div className="mt-2 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold tracking-tight text-white">صندوق المحادثات <span className="text-slate-500">/ Inbox</span></h1><p className="mt-2 text-sm leading-6 text-slate-400">راقب الرحلة من أول سؤال إلى الحل أو التحويل للموظف المناسب.</p></div><div className="flex items-center gap-3 text-xs text-slate-400"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-lime-300" /> {conversations.filter(c => c.status === "active").length} نشطة</span><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-amber-300" /> {conversations.filter(c => c.status === "escalated").length} تصعيد</span></div></div></header>
    <div className="grid min-h-[620px] gap-5 xl:grid-cols-[360px_1fr]">
      <Card className="border-white/10 bg-[#0b1728]/90"><CardHeader className="border-b border-white/10 pb-4"><div className="flex items-center justify-between"><CardTitle className="text-base text-white">كل المحادثات</CardTitle><Inbox className="h-4 w-4 text-cyan-300" /></div></CardHeader><CardContent className="p-2">{isLoading && <p className="p-6 text-center text-sm text-slate-400">جاري تحميل المحادثات...</p>}{conversations.map(conversation => { const Icon = channelIcon[conversation.channel] || MessageCircle; return <button key={conversation.id} onClick={() => setSelectedId(conversation.id)} className={`w-full rounded-2xl p-4 text-right transition ${selectedId === conversation.id ? "bg-cyan-300/[0.09]" : "hover:bg-white/[0.04]"}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-white/[0.06] text-cyan-200"><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold text-white">{conversation.customerName || "زائر جديد"}</p><Badge className={conversation.status === "escalated" ? "border-amber-300/20 bg-amber-300/10 text-[10px] text-amber-200" : conversation.status === "resolved" ? "border-emerald-300/20 bg-emerald-300/10 text-[10px] text-emerald-200" : "border-cyan-300/20 bg-cyan-300/10 text-[10px] text-cyan-200"}>{conversation.status}</Badge></div><p className="mt-1 truncate text-xs text-slate-500">{conversation.customerEmail || conversation.customerPhone || `Conversation #${conversation.id}`}</p><div className="mt-2 flex items-center gap-2 text-[10px] text-slate-600"><span>{conversation.channel}</span><span>•</span><span>{new Date(conversation.updatedAt).toLocaleString()}</span></div></div></div></button>; })}{!conversations.length && !isLoading && <div className="px-6 py-16 text-center"><Inbox className="mx-auto h-9 w-9 text-slate-600" /><p className="mt-4 text-sm text-slate-300">صندوقك هادئ حالياً</p><p className="mt-1 text-xs text-slate-500">ستظهر هنا كل محادثة تصل عبر الويدجت أو القنوات.</p></div>}</CardContent></Card>
      <Card className="border-white/10 bg-[#0b1728]/90"><CardHeader className="flex flex-row items-center justify-between border-b border-white/10 pb-5"><div><CardTitle className="text-base text-white">تفاصيل المحادثة</CardTitle><p className="mt-1 text-xs text-slate-400">{detail?.conversation ? `#${detail.conversation.id} · ${detail.conversation.channel}` : "اختر محادثة من القائمة"}</p></div>{detail?.conversation && <div className="flex items-center gap-2"><Button onClick={() => setStatus("resolved")} variant="outline" className="h-9 rounded-xl border-emerald-300/20 bg-emerald-300/5 text-xs text-emerald-200 hover:bg-emerald-300/10"><CheckCircle2 className="ml-2 h-3.5 w-3.5" /> حل</Button><Button onClick={() => setStatus("escalated")} variant="outline" className="h-9 rounded-xl border-amber-300/20 bg-amber-300/5 text-xs text-amber-200 hover:bg-amber-300/10">تصعيد للبشر</Button></div>}</CardHeader><CardContent className="flex min-h-[520px] flex-col p-0">{detail?.conversation ? <><div className="flex items-center gap-3 border-b border-white/[0.07] px-6 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-cyan-300/20 to-lime-300/10 text-cyan-100"><UserRound className="h-4 w-4" /></div><div><p className="text-sm font-medium text-white">{detail.conversation.customerName || "زائر جديد"}</p><p className="mt-1 text-xs text-slate-500">{detail.conversation.customerEmail || detail.conversation.customerPhone || "لم يشارك بيانات التواصل"}</p></div></div><div className="flex-1 space-y-4 overflow-y-auto p-6">{detail.messages.map(message => <div key={message.id} className={`flex ${message.sender === "customer" ? "justify-start" : "justify-end"}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.sender === "customer" ? "rounded-tr-md bg-white/[0.06] text-slate-200" : "rounded-tl-md bg-cyan-300/10 text-cyan-100"}`}><p className="mb-1 text-[10px] uppercase tracking-wider text-slate-500">{message.sender}</p>{message.content}</div></div>)}{!detail.messages.length && <p className="text-center text-sm text-slate-500">لا توجد رسائل محفوظة في هذه المحادثة.</p>}</div><div className="border-t border-white/[0.07] px-6 py-4 text-xs text-slate-500">الردود البشرية تُدار حالياً من نظامك الخارجي. نقطة التصعيد محفوظة لمتابعة الفريق.</div></> : <div className="flex flex-1 flex-col items-center justify-center text-center"><MessageCircle className="h-10 w-10 text-slate-600" /><p className="mt-4 text-sm text-slate-300">اختر محادثة لعرض سياقها</p><p className="mt-1 text-xs text-slate-500">كل الرسائل محمية ضمن مساحة العمل الحالية.</p></div>}</CardContent></Card>
    </div>
  </div>;
}
