import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BookOpenText, FileText, Plus, Search, Sparkles, UploadCloud } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Knowledge() {
  const utils = trpc.useUtils();
  const { data: agents = [] } = trpc.agents.list.useQuery();
  const [agentId, setAgentId] = useState<number | undefined>();
  const [query, setQuery] = useState("");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [category, setCategory] = useState("FAQ");
  useEffect(() => { if (!agentId && agents[0]) setAgentId(agents[0].id); }, [agents, agentId]);
  const { data: items = [], isLoading } = trpc.knowledge.list.useQuery({ agentId: agentId as number }, { enabled: Boolean(agentId) });
  const createMutation = trpc.knowledge.create.useMutation({ onSuccess: async () => { await utils.knowledge.list.invalidate(); setTitle(""); setContent(""); toast.success("تمت إضافة المادة إلى قاعدة المعرفة"); }, onError: error => toast.error(error.message) });
  const deleteMutation = trpc.knowledge.delete.useMutation({ onSuccess: async () => { await utils.knowledge.list.invalidate(); toast.success("تم حذف العنصر"); }, onError: error => toast.error(error.message) });
  const filtered = items.filter(item => `${item.title} ${item.content} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const addItem = () => { if (!agentId) return toast.error("اختر وكيلاً أولاً"); createMutation.mutate({ agentId, title, content, category }); };
  const loadFile = async (file?: File) => { if (!file) return; const text = await file.text(); setTitle(file.name.replace(/\.[^/.]+$/, "")); setContent(text); toast.success("تم تحميل النص من الملف — راجعه قبل الحفظ"); };

  return <div className="mx-auto max-w-[1400px] space-y-7 pb-12" dir="rtl">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300/80" dir="ltr">Knowledge Hub / 02</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">قاعدة المعرفة <span className="text-slate-500">/ Knowledge</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">أعطِ الوكيل سياق عملك الحقيقي ليجيب بثقة، ويعرف ما الذي يقوله ومتى يحوّل العميل إلى فريقك.</p></div><div className="flex items-center gap-3"><select value={agentId ?? ""} onChange={e => setAgentId(Number(e.target.value))} className="h-10 rounded-xl border border-white/10 bg-white/[0.05] px-3 text-sm text-white outline-none"><option value="" className="bg-[#0b1728]">اختر الوكيل</option>{agents.map(agent => <option key={agent.id} value={agent.id} className="bg-[#0b1728]">{agent.name}</option>)}</select><Button onClick={() => document.getElementById("knowledge-form")?.scrollIntoView({ behavior: "smooth" })} className="rounded-xl bg-lime-300 text-slate-950 hover:bg-lime-200"><Plus className="ml-2 h-4 w-4" /> إضافة معرفة</Button></div></header>
    <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
      <Card id="knowledge-form" className="h-fit border-white/10 bg-[#0b1728]/90"><CardHeader className="border-b border-white/10 pb-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-lime-300/10 text-lime-300"><Sparkles className="h-5 w-5" /></div><div><CardTitle className="text-base text-white">أضف مصدراً جديداً</CardTitle><p className="mt-1 text-xs text-slate-400">FAQ أو سياسة أو معلومة منتج</p></div></div></CardHeader><CardContent className="space-y-4 p-5"><label className="block space-y-2"><span className="text-xs text-slate-300">العنوان / Title</span><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: سياسة الاسترجاع" className="border-white/10 bg-white/[0.04] text-white" /></label><label className="block space-y-2"><span className="text-xs text-slate-300">التصنيف / Category</span><Input value={category} onChange={e => setCategory(e.target.value)} placeholder="FAQ" className="border-white/10 bg-white/[0.04] text-white" /></label><label className="block space-y-2"><span className="text-xs text-slate-300">المحتوى / Content</span><Textarea value={content} onChange={e => setContent(e.target.value)} rows={9} placeholder="اكتب السؤال والجواب أو الصق معلومات عملك هنا..." className="resize-none border-white/10 bg-white/[0.04] text-white" /></label><div className="rounded-2xl border border-dashed border-white/15 bg-white/[0.025] p-4"><label className="flex cursor-pointer items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-300"><UploadCloud className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-medium text-white">تحميل ملف نصي</p><p className="mt-1 text-xs text-slate-500">TXT، MD، CSV — يُقرأ محلياً قبل الحفظ</p></div><input type="file" accept=".txt,.md,.csv" className="hidden" onChange={e => loadFile(e.target.files?.[0])} /></label></div><Button onClick={addItem} disabled={!title || content.length < 10 || createMutation.isPending} className="w-full rounded-xl bg-cyan-300 text-slate-950 hover:bg-cyan-200"><BookOpenText className="ml-2 h-4 w-4" /> حفظ في قاعدة المعرفة</Button></CardContent></Card>
      <Card className="border-white/10 bg-[#0b1728]/90"><CardHeader className="flex flex-row items-center justify-between border-b border-white/10 pb-5"><div><CardTitle className="text-base text-white">المصادر الحالية</CardTitle><p className="mt-1 text-xs text-slate-400">{items.length} مصدر مرتبط بالوكيل المحدد</p></div><div className="relative w-48"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="بحث..." className="h-9 border-white/10 bg-white/[0.04] pr-9 text-xs text-white" /></div></CardHeader><CardContent className="p-4">{isLoading && <p className="p-6 text-center text-sm text-slate-400">جاري تحميل المصادر...</p>}{filtered.map(item => <div key={item.id} className="group border-b border-white/[0.07] px-2 py-5 last:border-0"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-300"><FileText className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold text-white">{item.title}</h3><Badge className="border-white/10 bg-white/[0.06] text-[10px] text-slate-300">{item.category}</Badge></div><Button variant="ghost" size="sm" onClick={() => deleteMutation.mutate({ id: item.id })} className="h-7 text-xs text-rose-400 hover:bg-rose-500/10 hover:text-rose-300">حذف</Button></div><p className="mt-2 line-clamp-3 whitespace-pre-line text-xs leading-6 text-slate-400">{item.content}</p></div></div></div>)}{!filtered.length && !isLoading && <div className="px-6 py-16 text-center"><BookOpenText className="mx-auto h-10 w-10 text-slate-600" /><p className="mt-4 text-sm text-slate-300">لا توجد مصادر مطابقة</p><p className="mt-1 text-xs text-slate-500">أضف أول FAQ أو معلومة حتى يصبح الوكيل أكثر دقة.</p></div>}</CardContent></Card>
    </div>
  </div>;
}
