import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ChartNoAxesCombined, Loader2, Target, UserRoundCheck } from "lucide-react";
import { useEffect, useState } from "react";

export default function Quality() {
  const agentsQuery = trpc.agents.list.useQuery();
  const [agentId, setAgentId] = useState<number | null>(null);
  useEffect(() => {
    if (!agentId && agentsQuery.data?.[0]?.id) setAgentId(agentsQuery.data[0].id);
  }, [agentId, agentsQuery.data]);
  const qualityQuery = trpc.agents.quality.useQuery({ agentId: agentId || 0 }, { enabled: Boolean(agentId) });
  const quality = qualityQuery.data;

  return <div className="mx-auto max-w-[1180px] space-y-7 pb-12" dir="rtl">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-300/80" dir="ltr">Quality / opportunities</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">جودة الوكيل وفرص العملاء</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">راقب ما إذا كانت المحادثات ذات نية تجارية تنتهي ببيانات تواصل محفوظة أو تنتهي كفرص تحتاج متابعة. جميع المقاييس تُستخرج من المحادثات والعملاء المحتملين المسجلين، وليست تقديرات تسويقية.</p></div><div className="min-w-[230px]"><label className="mb-2 block text-xs font-medium text-slate-400">اختر الوكيل</label><select value={agentId || ""} onChange={event => setAgentId(Number(event.target.value))} className="h-10 w-full rounded-xl border border-white/10 bg-[#0b1728] px-3 text-sm text-white outline-none focus:border-cyan-300"><option value="" disabled>اختر وكيلاً</option>{agentsQuery.data?.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></div></header>

    {agentsQuery.isLoading || qualityQuery.isLoading ? <Card className="border-white/10 bg-[#0b1728]/90"><CardContent className="flex items-center gap-3 p-7 text-sm text-slate-400"><Loader2 className="h-5 w-5 animate-spin text-cyan-300" /> جارٍ تحميل مؤشرات الجودة...</CardContent></Card> : !agentId ? <Card className="border-dashed border-white/15 bg-white/[0.02]"><CardContent className="p-8 text-center text-sm text-slate-400">أنشئ وكيلاً أولاً لتظهر مؤشرات فرص العملاء.</CardContent></Card> : quality ? <>
      <div className="grid gap-4 md:grid-cols-3"><Card className="border-lime-300/20 bg-gradient-to-br from-lime-300/[0.09] to-[#0b1728]/95"><CardContent className="p-5"><div className="flex items-start justify-between"><p className="text-sm text-slate-300">نسبة التقاط الفرص</p><Target className="h-5 w-5 text-lime-300" /></div><p className="mt-5 text-4xl font-semibold text-lime-200">{quality.captureRate}%</p><p className="mt-2 text-xs leading-5 text-slate-400">من فرص ذات نية تجارية ومحصورة بين فرصة ملتقطة أو فرصة منتهية بلا بيانات تواصل.</p></CardContent></Card><Card className="border-cyan-300/20 bg-gradient-to-br from-cyan-300/[0.08] to-[#0b1728]/95"><CardContent className="p-5"><div className="flex items-start justify-between"><p className="text-sm text-slate-300">عملاء محتملون ملتقطون</p><UserRoundCheck className="h-5 w-5 text-cyan-300" /></div><p className="mt-5 text-4xl font-semibold text-cyan-100">{quality.capturedLeadCount}</p><p className="mt-2 text-xs leading-5 text-slate-400">محادثات تجارية لها سجل عميل محتمل أو وسيلة تواصل محفوظة.</p></CardContent></Card><Card className="border-amber-300/20 bg-gradient-to-br from-amber-300/[0.08] to-[#0b1728]/95"><CardContent className="p-5"><div className="flex items-start justify-between"><p className="text-sm text-slate-300">فرص تحتاج متابعة</p><AlertTriangle className="h-5 w-5 text-amber-300" /></div><p className="mt-5 text-4xl font-semibold text-amber-100">{quality.missedOpportunityCount}</p><p className="mt-2 text-xs leading-5 text-slate-400">طلبات تجارية مكتملة بلا وسيلة اتصال محفوظة؛ راجع مسار التأهيل أو التحويل.</p></CardContent></Card></div>
      <Card className="border-white/10 bg-[#0b1728]/90"><CardHeader className="border-b border-white/10 pb-4"><div className="flex items-center gap-3"><ChartNoAxesCombined className="h-5 w-5 text-cyan-300" /><div><CardTitle className="text-base text-white">التقاط الفرص بحسب القناة</CardTitle><p className="mt-1 text-xs text-slate-400">تُحتسب النية التجارية من نص العميل، ثم تقارنها المنصة بسجل العميل المحتمل أو وسيلة التواصل المحفوظة في نفس المحادثة.</p></div></div></CardHeader><CardContent className="p-5">{quality.channelCaptureMetrics.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{quality.channelCaptureMetrics.map(channel => <div key={channel.channel} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex items-center justify-between"><p className="font-semibold text-white">{channel.channel}</p><Badge className="border-cyan-300/20 bg-cyan-300/[0.08] text-cyan-100">{channel.conversations} محادثة</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-lg font-semibold text-lime-200">{channel.captureRate}%</p><p className="mt-1 text-[10px] text-slate-500">التقاط</p></div><div><p className="text-lg font-semibold text-cyan-100">{channel.captured}</p><p className="mt-1 text-[10px] text-slate-500">ملتقط</p></div><div><p className="text-lg font-semibold text-amber-200">{channel.missed}</p><p className="mt-1 text-[10px] text-slate-500">للمتابعة</p></div></div></div>)}</div> : <div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">لا توجد محادثات مسجلة لهذا الوكيل حتى الآن.</div>}</CardContent></Card>
    </> : <Card className="border-rose-400/20 bg-rose-400/[0.06]"><CardContent className="p-6 text-sm text-rose-200">تعذر تحميل مؤشرات فرص العملاء لهذا الوكيل.</CardContent></Card>}
  </div>;
}
