-- Neon AI Agent Platform: initial PostgreSQL schema for Supabase.
-- This migration creates an empty, tenant-isolated schema only. It never copies
-- or deletes data from the existing MySQL/TiDB production database.

create or replace function public.neon_set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create table public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role text not null default 'user' check (role in ('user', 'admin')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table public.tenants (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  "ownerId" integer not null references public.users(id) on delete restrict,
  slug varchar(100) not null unique,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.tenant_data_policies (
  id integer generated by default as identity primary key,
  "tenantId" integer not null unique references public.tenants(id) on delete cascade,
  "retentionDays" integer not null default 90 check ("retentionDays" between 1 and 3650),
  "requireConsent" boolean not null default true,
  "allowModelTraining" boolean not null default false,
  "sectorProfile" varchar(32) not null default 'general' check ("sectorProfile" in ('general', 'healthcare', 'finance', 'legal')),
  "minimizeSensitiveData" boolean not null default false,
  "requireSensitiveHumanReview" boolean not null default false,
  "deletionContactEmail" varchar(320),
  "updatedAt" timestamptz not null default now()
);

create table public.agents (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  name varchar(255) not null,
  description text,
  persona text,
  tone varchar(50) not null default 'professional',
  language varchar(10) not null default 'ar',
  "llmModel" varchar(100) not null default 'claude-haiku-4-5',
  "decisionRules" text,
  "fallbackMessage" text,
  "escalationKeyword" varchar(100) not null default 'موظف,human,agent',
  "capabilitiesJson" jsonb,
  "sourceWebsiteUrl" text,
  "lastWebsiteSyncAt" timestamptz,
  "syncCronTaskUid" varchar(65),
  "syncIntervalHours" integer not null default 24 check ("syncIntervalHours" between 1 and 720),
  status text not null default 'active' check (status in ('active', 'paused', 'draft')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.knowledge_base (
  id integer generated by default as identity primary key,
  "agentId" integer not null references public.agents(id) on delete cascade,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  title varchar(255) not null,
  content text not null,
  category varchar(100) not null default 'FAQ',
  "sourceUrl" text,
  "sourceTitle" varchar(255),
  "sourceFetchedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.conversations (
  id integer generated by default as identity primary key,
  "agentId" integer not null references public.agents(id) on delete restrict,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  channel varchar(50) not null default 'web',
  "customerName" varchar(255),
  "customerEmail" varchar(320),
  "customerPhone" varchar(50),
  status text not null default 'active' check (status in ('active', 'escalated', 'resolved')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.messages (
  id integer generated by default as identity primary key,
  "conversationId" integer not null references public.conversations(id) on delete cascade,
  sender text not null check (sender in ('customer', 'agent', 'system', 'human')),
  content text not null,
  "createdAt" timestamptz not null default now()
);

create table public.leads (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "agentId" integer not null references public.agents(id) on delete restrict,
  "conversationId" integer references public.conversations(id) on delete set null,
  name varchar(255) not null,
  email varchar(320),
  phone varchar(50),
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'closed')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.team_members (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "userId" integer references public.users(id) on delete set null,
  name varchar(255) not null,
  email varchar(320) not null,
  role text not null default 'agent' check (role in ('owner', 'admin', 'agent', 'viewer')),
  status text not null default 'active' check (status in ('active', 'invited', 'suspended')),
  availability text not null default 'online' check (availability in ('online', 'offline', 'busy')),
  "lastActiveAt" timestamptz not null default now(),
  "idleTimeoutMinutes" integer not null default 15 check ("idleTimeoutMinutes" between 1 and 240),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("tenantId", email)
);

create table public.team_invites (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  email varchar(320) not null,
  role text not null default 'agent' check (role in ('admin', 'agent', 'viewer')),
  token varchar(64) not null unique,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'revoked')),
  "createdAt" timestamptz not null default now()
);

create table public.team_member_assignments (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "memberId" integer not null references public.team_members(id) on delete cascade,
  "targetType" text not null check ("targetType" in ('agent', 'channel')),
  "targetId" varchar(100) not null,
  "createdAt" timestamptz not null default now(),
  unique ("tenantId", "memberId", "targetType", "targetId")
);

create table public.workspace_notifications (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "memberId" integer references public.team_members(id) on delete set null,
  title varchar(255) not null,
  message text not null,
  type text not null default 'escalation' check (type in ('escalation', 'assignment', 'lead', 'general')),
  "isRead" boolean not null default false,
  "createdAt" timestamptz not null default now()
);

create table public.push_subscriptions (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "memberId" integer references public.team_members(id) on delete set null,
  endpoint text not null,
  p256dh varchar(255) not null,
  auth varchar(255) not null,
  "createdAt" timestamptz not null default now(),
  unique (endpoint)
);

create table public.notification_preferences (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "userId" integer not null references public.users(id) on delete cascade,
  "escalationPush" boolean not null default true,
  "assignmentPush" boolean not null default true,
  "leadPush" boolean not null default true,
  "generalPush" boolean not null default true,
  "soundAlerts" boolean not null default true,
  "updatedAt" timestamptz not null default now(),
  unique ("tenantId", "userId")
);

create table public.channel_integrations (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "agentId" integer not null references public.agents(id) on delete cascade,
  channel varchar(50) not null,
  "isActive" boolean not null default false,
  "configJson" jsonb,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("agentId", channel)
);

create table public.whatsapp_embedded_credentials (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "channelIntegrationId" integer not null references public.channel_integrations(id) on delete cascade,
  "whatsappBusinessAccountId" varchar(100) not null,
  "phoneNumberId" varchar(100) not null,
  "businessPortfolioId" varchar(100),
  "encryptedBusinessToken" text not null,
  "tokenVersion" varchar(20) not null default 'v1',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("channelIntegrationId")
);

create table public.onboarding_drafts (
  id integer generated by default as identity primary key,
  "tenantId" integer not null unique references public.tenants(id) on delete cascade,
  "payloadJson" jsonb not null,
  "updatedAt" timestamptz not null default now()
);

create table public.website_snapshots (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "agentId" integer not null references public.agents(id) on delete cascade,
  "websiteUrl" text not null,
  "analysisJson" text not null,
  "changesDetected" boolean not null default false,
  "changesSummary" text,
  "createdAt" timestamptz not null default now()
);

create table public.subscriptions (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "planName" varchar(50) not null default 'starter',
  status text not null default 'incomplete' check (status in ('active', 'trialing', 'past_due', 'canceled', 'incomplete')),
  "billingCycle" text not null default 'monthly' check ("billingCycle" in ('trial', 'monthly', 'yearly')),
  amount integer not null check (amount >= 0),
  currency varchar(10) not null default 'SAR',
  "hyperPayCheckoutId" varchar(255),
  "currentPeriodStart" timestamptz,
  "currentPeriodEnd" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.payment_transactions (
  id integer generated by default as identity primary key,
  "tenantId" integer not null references public.tenants(id) on delete cascade,
  "subscriptionId" integer references public.subscriptions(id) on delete set null,
  "checkoutId" varchar(255) not null,
  "paymentId" varchar(255),
  amount integer not null check (amount >= 0),
  currency varchar(10) not null default 'SAR',
  status text not null default 'pending' check (status in ('pending', 'success', 'failed', 'refunded')),
  "responseCode" varchar(50),
  "responseMessage" text,
  "gatewayResponseJson" text,
  "createdAt" timestamptz not null default now(),
  unique ("checkoutId")
);

create index agents_tenant_id_idx on public.agents ("tenantId");
create index knowledge_base_tenant_agent_idx on public.knowledge_base ("tenantId", "agentId");
create index conversations_tenant_agent_idx on public.conversations ("tenantId", "agentId", "createdAt" desc);
create index messages_conversation_idx on public.messages ("conversationId", "createdAt");
create index leads_tenant_agent_idx on public.leads ("tenantId", "agentId", "createdAt" desc);
create index notifications_tenant_member_idx on public.workspace_notifications ("tenantId", "memberId", "createdAt" desc);
create index snapshots_tenant_agent_idx on public.website_snapshots ("tenantId", "agentId", "createdAt" desc);
create index subscriptions_tenant_idx on public.subscriptions ("tenantId", "createdAt" desc);

create trigger users_set_updated_at before update on public.users for each row execute function public.neon_set_updated_at();
create trigger tenants_set_updated_at before update on public.tenants for each row execute function public.neon_set_updated_at();
create trigger policies_set_updated_at before update on public.tenant_data_policies for each row execute function public.neon_set_updated_at();
create trigger agents_set_updated_at before update on public.agents for each row execute function public.neon_set_updated_at();
create trigger knowledge_set_updated_at before update on public.knowledge_base for each row execute function public.neon_set_updated_at();
create trigger conversations_set_updated_at before update on public.conversations for each row execute function public.neon_set_updated_at();
create trigger leads_set_updated_at before update on public.leads for each row execute function public.neon_set_updated_at();
create trigger team_members_set_updated_at before update on public.team_members for each row execute function public.neon_set_updated_at();
create trigger notification_preferences_set_updated_at before update on public.notification_preferences for each row execute function public.neon_set_updated_at();
create trigger channels_set_updated_at before update on public.channel_integrations for each row execute function public.neon_set_updated_at();
create trigger credentials_set_updated_at before update on public.whatsapp_embedded_credentials for each row execute function public.neon_set_updated_at();
create trigger onboarding_drafts_set_updated_at before update on public.onboarding_drafts for each row execute function public.neon_set_updated_at();
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.neon_set_updated_at();

-- The browser has no direct table access. The existing server remains the only
-- data access layer until a separately reviewed Supabase Auth migration.
alter table public.users enable row level security;
alter table public.tenants enable row level security;
alter table public.tenant_data_policies enable row level security;
alter table public.agents enable row level security;
alter table public.knowledge_base enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.leads enable row level security;
alter table public.team_members enable row level security;
alter table public.team_invites enable row level security;
alter table public.team_member_assignments enable row level security;
alter table public.workspace_notifications enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.channel_integrations enable row level security;
alter table public.whatsapp_embedded_credentials enable row level security;
alter table public.onboarding_drafts enable row level security;
alter table public.website_snapshots enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payment_transactions enable row level security;
